<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVgj6OW0\Eccube_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVgj6OW0/Eccube_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVgj6OW0.legacy');

    return;
}

if (!\class_exists(Eccube_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVgj6OW0\Eccube_KernelDevDebugContainer::class, Eccube_KernelDevDebugContainer::class, false);
}

return new \ContainerVgj6OW0\Eccube_KernelDevDebugContainer([
    'container.build_hash' => 'Vgj6OW0',
    'container.build_id' => '4eb1bf71',
    'container.build_time' => 1700797129,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVgj6OW0');
