<?php

namespace ContainerBjUAxOf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSamplePageControllerService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the public 'Customize\Controller\SamplePageController' shared autowired service.
     *
     * @return \Customize\Controller\SamplePageController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Customize'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'SamplePageController.php';

        return $container->services['Customize\\Controller\\SamplePageController'] = new \Customize\Controller\SamplePageController();
    }
}
