<?php

namespace ContainerLNJE5ut;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCtypeRepositoryService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Eccube\Repository\Master\ctypeRepository' shared autowired service.
     *
     * @return \Eccube\Repository\Master\ctypeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'Master'.\DIRECTORY_SEPARATOR.'ctypeRepository.php';

        return $container->privates['Eccube\\Repository\\Master\\ctypeRepository'] = new \Eccube\Repository\Master\ctypeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
