<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBFfjmox\Eccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBFfjmox/Eccube_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerBFfjmox.legacy');

    return;
}

if (!\class_exists(Eccube_KernelProdContainer::class, false)) {
    \class_alias(\ContainerBFfjmox\Eccube_KernelProdContainer::class, Eccube_KernelProdContainer::class, false);
}

return new \ContainerBFfjmox\Eccube_KernelProdContainer([
    'container.build_hash' => 'BFfjmox',
    'container.build_id' => 'c7779e04',
    'container.build_time' => 1700793095,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBFfjmox');
