<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLNJE5ut\Eccube_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLNJE5ut/Eccube_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLNJE5ut.legacy');

    return;
}

if (!\class_exists(Eccube_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLNJE5ut\Eccube_KernelDevDebugContainer::class, Eccube_KernelDevDebugContainer::class, false);
}

return new \ContainerLNJE5ut\Eccube_KernelDevDebugContainer([
    'container.build_hash' => 'LNJE5ut',
    'container.build_id' => '399752e4',
    'container.build_time' => 1701155087,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLNJE5ut');
