<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYMpmxIx\Eccube_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYMpmxIx/Eccube_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYMpmxIx.legacy');

    return;
}

if (!\class_exists(Eccube_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYMpmxIx\Eccube_KernelDevDebugContainer::class, Eccube_KernelDevDebugContainer::class, false);
}

return new \ContainerYMpmxIx\Eccube_KernelDevDebugContainer([
    'container.build_hash' => 'YMpmxIx',
    'container.build_id' => '8e79e0f0',
    'container.build_time' => 1701053969,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYMpmxIx');
